### ISSUE TITLE
[suggestion] embedding cr4shed into Preference

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [Muirey03/Cr4shed#7]
Instead of creating a full-fledge application, embedding cr4shed into Preference as a preference bundle in my opinion is more elegant.
Because Preference.app is a system app so
```
cy# [[NSFileManager defaultManager] contentsOfDirectoryAtPath:@"/var/tmp/crash_logs" error:nil]
@[]
```
listing directory is not a problem.

**Comment by NSExceptional** [comment]
I personally don't think it belongs in system preferences; it provides notifications, for example. Having it as it's own app also makes maintenance easier, because if the System Preferences app changes drastically, it won't break this app.

Judging from the lack of response by @Muirey03 I'm gonna guess that this is a non-goal for this project, so I'll close this for now.
